config/routes.rb
Rails.application.routes.draw do
  # Route for showing authors
  get '/authors/:author_name', to: 'authors#show', as: :author

  # Route for showing books by genre
  get '/books/by_genre', to: 'books#show_by_genre', as: :books_by_genre

  # Route for showing books by publisher
  get '/publishers/:publisher', to: 'books#show_by_publisher', as: :books_by_publisher

  # Route for searching books
  get '/books/search', to: 'books#search', as: :book_search

  # Existing route for showing books by author
  get '/authors/:author_name/books', to: 'books#show_by_author', as: :books_by_author

  # Resourceful routes for genres, books, favorites, users, and other paths
  resources :genres, only: [:show]
  resources :books, only: [:index, :show] do
    resources :reviews, only: [:create, :new]
  end
  resources :favorites, only: [:new, :create]
  resources :users, only: [:show]

  # Other routes...
  root 'books#index'
  get 'about', to: 'about#index'
  get 'collection', to: 'books#collection'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  # Associations
  has_many :reviews
  has_many :favorites
  has_many :users, through: :favorites

  # Validations
  validates :title, :genre, :height, :publisher, :author, presence: true

  # Search method to filter books by title and genre
  def self.search(query, genre)
    books = all
    books = books.where("title LIKE ?", "%#{query.downcase}%") if query.present?
    books = books.where(genre: genre) if genre.present?
    books
    
  end 
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :user_id, uniqueness: { scope: :book_id, message: "already favorited this book" }
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books 
    
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :favorites
    has_many :books, through: :favorites
  
    validates :username, :email, presence: true
    validates :email, uniqueness: true
  end

app/controllers/about_controller.rb
# app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
    
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @books = Book.where(author: params[:author])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @books = @books.where(genre: params[:genre]) if params[:genre].present?
    @books = @books.where("LOWER(title) LIKE ?", "%#{params[:query].downcase}%") if params[:query].present?
    @books = @books.page(params[:page]).per(10)
  end

  def show
    @book = Book.find(params[:id])
  end

  def show_by_author
    @books = Book.where(author: params[:author_name]).page(params[:page]).per(10).distinct
    render :index
  end

  def show_by_genre
    puts "Received genre parameter: #{params[:genre]}"
    @books = Book.where(genre: params[:genre]).page(params[:page]).per(10).distinct
    render :index
  end

  def show_by_publisher
    @books = Book.where(publisher: params[:publisher]).page(params[:page]).per(10).distinct
    render :index
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :publisher)
  end
  
end

app/controllers/genres_controller.rb
# app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @books = @genre.books
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/about/index.html.erb
<!-- app/views/about/index.html.erb -->
<h1>About Page</h1>
<p>Add details about your data sources here.</p>

app/views/books/collection.html.erb
<!-- app/views/books/collection.html.erb -->

<h1>Collection Navigation</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Publisher</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.publisher %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/books/index.html.erb
<div class="container">
  <h1>All Books</h1>

  <%= form_tag(books_path, method: "get") do %>
    <div class="row">
      <div class="col-md-6">
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search by title" %>
      </div>
      <div class="col-md-4">
        <%= select_tag :genre, options_for_select([["All Genres", ""]] + Genre.pluck(:name, :name), params[:genre]), include_blank: true, class: "form-select" %>
      </div>
      <div class="col-md-2">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <% if @books.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Genre</th>
          <th>Publisher</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= link_to book.author, books_by_author_path(author_name: book.author) %></td>
            <td>
              <% if book.genre.is_a?(String) %>
                <%= book.genre %>
              <% else %>
                <%= link_to book.genre.name, books_by_genre_path(genre: book.genre.name) %>
              <% end %>
            </td>
            <td><%= link_to book.publisher, books_by_publisher_path(publisher: book.publisher) %></td>
            <td><%= link_to "View", book_path(book) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @books %>
  <% else %>
    <p>No books found.</p>
  <% end %>

</div>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<div>
  <strong>Author:</strong> <%= @book.author %>
</div>

<div>
  <strong>Genre:</strong> <%= @book.genre %>
</div>

<div>
  <strong>Publisher:</strong> <%= @book.publisher %>
</div>

<div>
  <%= link_to "Back", books_path %>
</div>

app/views/favorites/index.html.erb
<h1>My Favorite Books</h1>
<ul>
  <% @user.favorites.each do |favorite| %>
    <li><%= link_to favorite.book.title, book_path(favorite.book) %></li>
  <% end %>
</ul>

app/views/genre/show.html.erb
<!-- app/views/genres/show.html.erb -->
<h1><%= @genre.name %></h1>

<h2>Books in this Genre</h2>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/genres/show.html.erb
<h1>Genres#show</h1>
<p>Find me in app/views/genres/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="<%= root_path %>">MyBooks</a>

        <!-- Toggler/collapsible Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>
            <!-- Add more menu items as needed -->
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <!-- Additional links for interacting with books -->
    <% if @controller_name == 'books' %>
      <div>
        <%= link_to "Add Review", @new_review_path %>
        <%= link_to "Add to Favorites", @new_favorite_path %>
      </div>
    <% end %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: [@book, @review]) do |form| %>
  <div>
    <%= form.label :rating %>
    <%= form.number_field :rating, min: 1, max: 5 %>
  </div>
  <div>
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>
  <%= form.submit %>
<% end %>

app/views/reviews/show.html.erb
<p><strong>Rating:</strong> <%= @review.rating %> stars</p>
<p><strong>Comment:</strong> <%= @review.comment %></p>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>
<p><strong>Email:</strong> <%= @user.email %></p>
<h2>My Reviews</h2>
<ul>
  <% @user.reviews.each do |review| %>
    <li>
      <%= link_to review.book.title, book_path(review.book) %> -
      <%= review.rating %> stars
    </li>
  <% end %>
</ul>